# Generated by Django 3.0.2 on 2020-01-15 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='deposit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 10, 29, 7, 968494)),
        ),
        migrations.AlterField(
            model_name='crop',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crops', to='api.Stock'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='api.Crop'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 10, 29, 7, 968494)),
        ),
    ]
