# Generated by Django 3.0.2 on 2020-01-15 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200115_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='crop',
            name='deposit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 11, 17, 16, 799991)),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 11, 17, 16, 799991)),
        ),
        migrations.AlterField(
            model_name='crop',
            name='coffee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.CoffeeType'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Farm'),
        ),
    ]
